---

# toggles to enable and disable various operations
toggles:
  # global toggles for (complete) playbooks
  enable_os: true
  enable_docker: true
  enable_hashicorp: true
  enable_podman: false
  os:
    install_packages: true
    remove_packages: true
    update_apt_cache: true
  docker:
    add_apt_repository: true
    create_group: true
    create_user: true
    install_packages: true
  hashicorp:
    # add HashiCorp APT repository
    add_apt_repository: true

    # add `nomad` user to `docker` group
    add_nomad_user_to_docker: true

    # copy unit files for enabled products
    copy_unit_files: true

    # create users for enabled products
    create_users: true

    # create groups for enabled products
    create_groups: true

    # enable services for enabled products
    enable_services: true

    # enable product-specific operations
    enabled:
      boundary: false
      consul: true
      nomad: true
      vault: false

    # install Nomad plugins
    install_nomad_plugins: true

    # install packages for enabled products
    install_packages: true

    # start services for enabled products
    start_services: true

  misc:
    # create files with version information
    create_versions_files: true

    # copy files with version information to image
    copy_versions_files: true

  podman:
    # install packages for Podman
    install_packages: false

apt_packages:
  to_install:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - jq
    - libcap2
    - lsb-release
    - sudo
    - unzip
  to_remove:
    - ftp
    - snapd
    - telnet

  # package definitions (name and version) for Docker
  docker:
    # see https://docs.docker.com/release-notes/
    - name: docker-ce
      version: "5:20.10.5*"

#    # see https://github.com/containerd/containerd/releases
#    - name: containerd
#      version: "1.4.4"

  # package definitions (name and version) for HashiCorp products
  hashicorp:
    # see https://releases.hashicorp.com/boundary/
    - name: boundary
      version: 0.1.8

    # see https://releases.hashicorp.com/consul/
    - name: consul
      version: 1.9.4

    # see https://releases.hashicorp.com/nomad/
    - name: nomad
      version: 1.0.4

    # see https://releases.hashicorp.com/vault/
    - name: vault
      version: 1.7.0

  # plugin definitions (name and version) for HashiCorp Nomad
  hashicorp_nomad_plugins:
    # see https://releases.hashicorp.com/nomad-driver-podman/
    - name: nomad-driver-podman
      version: 0.2.0

    # see https://releases.hashicorp.com/nomad-driver-lxc/
    - name: nomad-driver-lxc
      version: 0.1.0

    # see https://releases.hashicorp.com/nomad-autoscaler/
    - name: nomad-autoscaler
      version: 0.3.0

  # package definitions (name and version) for HashiCorp products
  podman:
    # see https://podman.io/releases/
    - name: podman
      version: 3.0.0

version_files:
  source: "../templates"
  destination: "../../generated"
  templates:
    - "versions.txt"
    - "versions.yml"

apt_repos:
  docker: "https://download.docker.com"
  hashicorp: "https://apt.releases.hashicorp.com"
