---

# toggles to enable and disable various operations
toggles:
  # global toggles for (complete) playbooks
  enable_base: true
  enable_docker: true
  enable_hashicorp: true
  enable_podman: true

  base:
    install_base_packages: true
    remove_extraneous_packages: true
    update_apt_cache: true
  docker:
    add_apt_repository: true
    install_packages: true
  hashicorp:
    add_apt_repository: true
    add_nomad_user_to_docker: true
    copy_unit_files: true
    create_users: true
    create_groups: true
    enable_services: true
    install_nomad_plugins: true
    install_packages: true
  podman:
    install_packages: true

# packages to install
apt_packages:
  base:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - jq
    - libcap2
    - lsb-release
    - osquery
    - sudo
    - unzip

  # packages that should be removed (if present)
  # NOTE: this list is not exhaustive
  remove:
    - ftp
    - snapd

  docker:
    # see https://docs.docker.com/release-notes/
    - name: docker-ce
      version: "5:20.10.5*"

#    - name: containerd
#      version: "1.4.4*"

  hashicorp:
    # see https://releases.hashicorp.com/boundary/
    - name: boundary
      version: 0.1.8

    # see https://releases.hashicorp.com/consul/
    - name: consul
      version: 1.9.4

    # see https://releases.hashicorp.com/nomad/
    - name: nomad
      version: 1.0.4

    # see https://releases.hashicorp.com/vault/
    - name: vault
      version: 1.7.0

  hashicorp_nomad_plugins:
    # see https://releases.hashicorp.com/nomad-driver-podman/
    - name: nomad-driver-podman
      version: 0.2.0

#    # see https://releases.hashicorp.com/nomad-driver-lxc/
#    - name: nomad-driver-lxc
#      version: 0.1.0

    # see https://releases.hashicorp.com/nomad-autoscaler/
    - name: nomad-autoscaler
      version: 0.3.0

  podman:
    # see https://podman.io/releases/
    - name: podman
      version: 3.0.0

apt_repos:
  docker: "https://download.docker.com"
  hashicorp: "https://apt.releases.hashicorp.com"
