---

# see https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Update APT cache
  apt:
    force_apt_get: true
    update_cache: true
    upgrade: "yes"

# see https://docs.ansible.com/ansible/2.9/modules/package_module.html
- name: Install base packages
  apt:
    force_apt_get: true
    name: "{{ apt_packages.base }}"
    state: present
    update_cache: true

# see https://docs.ansible.com/ansible/2.9/modules/package_module.html
- name: Remove extraneous packages
  apt:
    autoclean: true
    autoremove: true
    force_apt_get: true
    name: "{{ apt_packages.remove }}"
    state: absent
    update_cache: true

  # TODO: add support for specifying additional packages
