---

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/debug_module.html
- name: debug
  debug:
    msg: "included base.yml"
  when:
    - toggle.enable_debug_statements is defined
    - toggle.enable_debug_statements

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_module.html
- name: Update APT Cache
  apt:
    force_apt_get: true
    update_cache: true
    upgrade: "yes"
  when:
    - ansible_os_family == "Debian"
    - toggles.os.update_apt_cache

# see https://docs.ansible.com/ansible/2.10/modules/package_module.html
- name: Install Packages
  apt:
    force_apt_get: true
    name: "{{ packages.to_install }}"
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"
    - toggles.os.install_packages

# see https://docs.ansible.com/ansible/2.10/modules/package_module.html
- name: Remove Packages
  apt:
    autoclean: true
    autoremove: true
    force_apt_get: true
    name: "{{ packages.to_remove }}"
    state: absent
    update_cache: true
  when:
    - ansible_os_family == "Debian"
    - toggles.os.remove_packages

# see https://docs.ansible.com/ansible/2.10/modules/copy_module.html
# TODO: fix the `src` in a better way
- name: Copy Version Files
  copy:
    backup: false
    dest: "/tmp"
    force: true
    src: "../../{{ generated_files.versions }}"
  when:
    - toggles.misc.copy_versions_files
