---

# see https://docs.ansible.com/ansible/2.9/modules/apt_key_module.html
- name: Add APT Key for Docker repository
  apt_key:
    url: "{{ apt_repos.docker }}/linux/ubuntu/gpg"
    state: present
  when: toggles.docker.add_apt_repository

# see https://docs.ansible.com/ansible/2.9/modules/apt_repository_module.html
- name: Add APT repository for Docker packages
  apt_repository:
    repo: "deb [arch=amd64] {{ apt_repos.docker }}/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
    update_cache: true
  when: toggles.docker.add_apt_repository

# see https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Install Docker packages
  apt:
    force_apt_get: true
    install_recommends: true
    name: "{{ item.name }}={{ item.version | default('*') }}"
    state: present
    update_cache: true
  with_items: "{{ apt_packages.docker }}"
  when: toggles.docker.install_packages
