---

# see https://docs.ansible.com/ansible/2.9/modules/apt_key_module.html
- name: Add APT Key for HashiCorp repository
  apt_key:
    url: "{{ apt_repos.hashicorp }}/gpg"
    state: present
  when: toggles.hashicorp.add_apt_repository

# see https://docs.ansible.com/ansible/2.9/modules/apt_repository_module.html
- name: Add APT repository for HashiCorp packages
  apt_repository:
    repo: "deb [arch=amd64] {{ apt_repos.hashicorp }} {{ ansible_distribution_release | lower }} main"
    state: present
    update_cache: true
  when: toggles.hashicorp.add_apt_repository

# see https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Install HashiCorp packages
  apt:
    force_apt_get: true
    install_recommends: true
    name: "{{ item.name }}={{ item.version | default('*') }}"
    state: present
    update_cache: true
  with_items: "{{ apt_packages.hashicorp }}"
  when: toggles.hashicorp.install_packages

# TODO: ensure these packages are available
## see https://docs.ansible.com/ansible/2.9/modules/apt_module.html
#- name: Install HashiCorp Nomad plugins
#  apt:
#    force_apt_get: true
#    install_recommends: true
#    name: "{{ item.name }}={{ item.version | default('*') }}"
#    state: present
#    update_cache: true
#  with_items: "{{ apt_packages.hashicorp_nomad_plugins }}"
#  when: toggles.hashicorp.install_nomad_plugins

# see https://docs.ansible.com/ansible/2.9/modules/template_module.html
- name: Copy HashiCorp Unit Files
  template:
    src: ../templates/{{ item.name }}.service
    dest: /lib/systemd/system/{{ item.name }}.service
  with_items: "{{ apt_packages.hashicorp }}"
  when: toggles.hashicorp.copy_unit_files

# see https://docs.ansible.com/ansible/2.9/modules/systemd_module.html
#- name: Enable HashiCorp Services
#  systemd:
#    state: started
#    name: item.name
#  with_items: "{{ apt_packages.hashicorp }}"
#  when: toggles.hashicorp.enable_services

# TODO: consider adding a `hashicorp` group
# see https://docs.ansible.com/ansible/2.9/modules/group_module.html
- name: Add Groups
  group:
    name: "{{ item.name }}"
    state: present
    system: true
  with_items: "{{ apt_packages.hashicorp }}"
  when: toggles.hashicorp.create_groups

# TODO: add users to `hashicorp` group (if available)
# see https://docs.ansible.com/ansible/2.9/modules/user_module.html
- name: Add Users
  user:
    name: "{{ item.name }}"
    comment: "HashiCorp {{ item.name | capitalize }}"
    group: "{{ item.name }}"
    system: true
  with_items: "{{ apt_packages.hashicorp }}"
  when: toggles.hashicorp.create_users

# see https://docs.ansible.com/ansible/2.9/modules/user_module.html
- name: Add `nomad` User to `docker` Group
  user:
    name: nomad
    group: docker
    system: true
    grousp: docker
    append: true
  with_items: "{{ apt_packages.hashicorp }}"
  when:
    - docker.install_packages
    - hashicorp.create_users
    - hashicorp.add_nomad_user_to_docker
