---

- name: "Provision Packer image"
  hosts: default
  become: true

  tasks:
    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Include variables
      include_vars: _vars.yml

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage OS packages
      include: os.yml
      when: enable_os

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage HashiCorp packages
      include: hashicorp.yml
      when: enable_hashicorp

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage Docker packages
      include: docker.yml
      # TODO: make docker installation conditional
      when: enable_docker

#    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
#    - name: Manage Podman packages
#      include: podman.yml
#      # TODO: make podman installation conditional

    # TODO: harden image

    # TODO: optimize system settings

    # TODO: verify images with goss
