---

- name: "Provision Packer Image for Target `{{ build_target }}`"
  hosts: default
  become: true
  vars:
    ansible_required_version: "2.11.3"

    # `os_hardening` specific configuration, see https://github.com/dev-sec/ansible-collection-hardening/tree/master/roles/os_hardening
    os_auditd_enabled: false

  vars_files:
    - "../../generated/generated-configuration.yml"

  pre_tasks:
    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/fail_module.html
    - name: Verify Ansible Version meets requirements
      fail:
        msg: "Need v{{ ansible_required_version }}, got v{{ ansible_version.full }}"
      when: ansible_version.full < ansible_required_version

    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/debug_module.html
    - name: Print `ansible_env`
      debug:
        var: ansible_env
      when:
        - enable_debug_statements is defined
        - enable_debug_statements

  collections:
    # see https://github.com/dev-sec/ansible-collection-hardening/
    - devsec.hardening

  roles:
    # see https://github.com/dev-sec/ansible-collection-hardening/tree/master/roles/os_hardening
    - os_hardening

    # see https://github.com/dev-sec/ansible-collection-hardening/tree/master/roles/ssh_hardening
    # SSH hardening must be omitted when in a Vagrant context
    - role: ssh_hardening
      when: build_target != "vagrant"

  tasks:
    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/include_module.html
    - name: Manage OS Operations
      include: os.yml
      when:
        - os.enabled

    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/include_module.html
    - name: Manage Prompt Operations
      include: prompt.yml
      when:
        - prompt.enabled

    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/include_module.html
    - name: Manage Docker Operations
      include: docker.yml
      when:
        - docker.enabled

    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/include_module.html
    - name: Manage Podman Operations
      include: podman.yml
      when:
        - podman.enabled

    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/include_module.html
    - name: Manage HashiCorp Operations
      include: hashicorp.yml
      when:
        - hashicorp.enabled

    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/include_module.html
    - name: Manage osquery Operations
      include: osquery.yml
      when:
        - osquery.enabled

  post_tasks:
    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/include_module.html
    - name: Manage Validation Operations
      include: post_validation.yml

    # see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/include_module.html
    - name: Manage Cleanup Tasks
      include: post_cleanup.yml
