---

- name: "Provision Packer image"
  hosts: default
  become: true

  tasks:
    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Include variables
      include_vars: _vars.yml

#    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
#    - name: Manage base packages
#      include: base.yml
       # TODO: add support for specifying additional packages

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage HashiCorp packages
      include: hashicorp.yml

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage Docker packages
      include: docker.yml
      # TODO: make docker installation conditional

#    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
#    - name: Manage Podman packages
#      include: podman.yml
#      # TODO: make podman installation conditional

    # TODO: harden image

    # TODO: optimize system settings

    # TODO: verify images with goss
