---

- name: "Provision Packer image"
  hosts: default
  become: true

  tasks:
    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Include variables
      include_vars: _vars.yml

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage OS packages
      include: os.yml
      when: toggles.enable_os

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage Docker packages
      include: docker.yml
      when: toggles.enable_docker

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage Podman packages
      include: podman.yml
      when: toggles.enable_podman

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage HashiCorp packages
      include: hashicorp.yml
      when: toggles.enable_hashicorp

    # TODO: harden image

    # TODO: optimize system settings
