---

- name: "Provision Packer image"
  hosts: default
  become: true

  tasks:
    # see https://docs.ansible.com/ansible/2.9/modules/include_vars_module.html
    # TODO: move the `file` path to the `generated` directory
    - name: Include Packer-generated Variables
      include_vars:
        file: generated_configuration.yml

    # see https://docs.ansible.com/ansible/2.9/modules/debug_module.html
    - name: ansible_env
      debug:
        var: ansible_env
      when:
        - toggle.enable_debug_statements is defined
        - toggle.enable_debug_statements

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage OS Packages
      include: os.yml
      when: toggles.enable_os

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage Docker Packages
      include: docker.yml
      when: toggles.enable_docker

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage Podman Packages
      include: podman.yml
      when: toggles.enable_podman

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage HashiCorp Packages
      include: hashicorp.yml
      when: toggles.enable_hashicorp

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html
    - name: Manage miscellaneous Operations
      include: misc.yml
      when: toggles.enable_misc_operations

# TODO: harden image

# TODO: optimize system settings
