---

# see https://docs.ansible.com/ansible/2.9/modules/debug_module.html
- name: debug
  debug:
    msg: "included os.yml"
  when:
    - toggle.enable_debug_statements is defined
    - toggle.enable_debug_statements

# see https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Update APT cache
  apt:
    force_apt_get: true
    update_cache: true
    upgrade: "yes"
  when:
    - ansible_os_family == "Ubuntu"
    - toggles.os.update_apt_cache

# see https://docs.ansible.com/ansible/2.9/modules/package_module.html
- name: Install Packages
  apt:
    force_apt_get: true
    name: "{{ packages.to_install }}"
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Ubuntu"
    - toggles.os.install_packages

# see https://docs.ansible.com/ansible/2.9/modules/package_module.html
- name: Remove Packages
  apt:
    autoclean: true
    autoremove: true
    force_apt_get: true
    name: "{{ packages.to_remove }}"
    state: absent
    update_cache: true
  when:
    - ansible_os_family == "Ubuntu"
    - toggles.os.remove_packages
