---

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_key_module.html
- name: Add APT Key for osquery Repository
  apt_key:
    keyserver: "{{ apt_repos.osquery.key_server }}"
    id: "{{ apt_repos.osquery.key }}"
    state: present
  when:
    - ansible_os_family == "Debian"
    - toggles.osquery.add_apt_repository

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_repository_module.html
- name: Add APT repository for osquery Packages
  apt_repository:
    filename: osquery
    repo: "deb [arch=amd64] {{ apt_repos.osquery.url }} deb main"
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"
    - toggles.osquery.add_apt_repository

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_module.html
- name: Install osquery Packages
  apt:
    force_apt_get: true
    install_recommends: true
    name: "osquery"
    state: present
    update_cache: true
  with_items: "{{ packages.osquery }}"
  when:
    - ansible_os_family == "Debian"
    - toggles.osquery.install_packages

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/file_module.html
- name: delete osquery directories
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ osquery.directories }}"
  when:
    - toggles.osquery.remove_directories
