---

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_key_module.html
- name: Add APT Key for osquery Repository
  apt_key:
    keyserver: "{{ osquery.repository.key_server }}"
    id: "{{ osquery.repository.key }}"
    state: present
  when:
    - ansible_os_family == "Debian"
    - osquery.toggles.add_repository

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_repository_module.html
- name: Add APT Repository for osquery Packages
  apt_repository:
    filename: osquery
    repo: "deb [arch=amd64] {{ osquery.repository.url }} deb main"
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"
    - osquery.toggles.add_repository

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_module.html
- name: Install osquery Packages
  apt:
    force_apt_get: true
    install_recommends: true
    name: "{{ item.name }}"
    state: present
    update_cache: true
  with_items:
    - "{{ osquery.packages }}"
  when:
    - ansible_os_family == "Debian"
    - osquery.toggles.install_packages

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/file_module.html
- name: Remove osquery Paths
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ osquery.paths }}"
  when:
    - osquery.toggles.remove_paths
