---

# see https://docs.ansible.com/ansible/2.9/modules/debug_module.html
- name: debug
  debug:
    msg: "included podman.yml"
  when:
    - toggle.enable_debug_statements is defined
    - toggle.enable_debug_statements

# see https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Install Podman packages
  apt:
    force_apt_get: true
    install_recommends: true
    name: "{{ item.name }}={{ item.version | default('*') }}"
    state: present
    update_cache: true
  with_items: "{{ packages.podman }}"
  when: toggles.podman.install_packages
