---

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/debug_module.html
- name: debug
  debug:
    msg: "included podman.yml"
  when:
    - toggle.enable_debug_statements is defined
    - toggle.enable_debug_statements

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_key_module.html
- name: Add APT Key for Podman Repository
  apt_key:
    state: present
    url: "{{ apt_repos.podman.url }}/Release.key"
  when:
    - ansible_os_family == "Debian"
    - toggles.podman.add_apt_repository

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_repository_module.html
- name: Add APT repository for Podman Packages
  apt_repository:
    filename: podman
    repo: "deb [arch=amd64] {{ apt_repos.podman.url }} stable"
    state: present
    update_cache: true
  when:
    - ansible_os_family == "Debian"
    - toggles.podman.add_apt_repository

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/apt_module.html
- name: Install Podman Packages
  apt:
    force_apt_get: true
    install_recommends: true
    name: "{{ item.name }}={{ item.version | default('*') }}"
    state: present
    update_cache: true
  with_items: "{{ packages.podman }}"
  when:
    - ansible_os_family == "Debian"
    - toggles.podman.install_packages
