---

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/debug_module.html
- name: debug
  debug:
    msg: "included post_validation.yml"
  when:
    - enable_debug_statements is defined
    - enable_debug_statements

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/include_role_module.html
- name: "Execute Ansible Roles"
  include_role:
    # see https://galaxy.ansible.com/naftulikay/degoss
    name: naftulikay.degoss
  when:
    - enable_post_validation is defined
    - enable_post_validation
