---

# see https://docs.ansible.com/ansible/2.10/collections/ansible/builtin/debug_module.html
- name: debug
  debug:
    msg: "included prompt.yml"
  when:
    - enable_debug_statements is defined
    - enable_debug_statements

