---

packages:
  base:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - libcap2
    - lsb-release
    - sudo

  # see https://docs.docker.com/release-notes/ for version information
  docker:
    - "docker-ce=5:20.10.5*"
    - "containerd.io=1.4.4-1"

  # see https://releases.hashicorp.com for version information
  hashicorp:
    - "boundary=0.1.8"
    - "consul=1.9.4"
    - "nomad=1.0.4"
    - "vault=1.7.0"

apt_repos:
  docker: "https://download.docker.com"
  hashicorp: "https://apt.releases.hashicorp.com"
