---

# see https://docs.ansible.com/ansible/2.9/modules/apt_key_module.html
- name: Add APT Key for Docker repository
  apt_key:
    url: "{{ apt_repos.docker }}/linux/ubuntu/gpg"
    state: present

# see https://docs.ansible.com/ansible/2.9/modules/apt_repository_module.html
- name: Add APT repository for Docker packages
  apt_repository:
    repo: "deb [arch=amd64] {{ apt_repos.docker }} {{ ansible_distribution_release | lower }} stable"
    state: present
    update_cache: true
    validate_certs: true

# see https://docs.ansible.com/ansible/2.9/modules/package_module.html
- name: Install Docker packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages.docker }}"
