---

# see https://docs.ansible.com/ansible/2.9/modules/apt_key_module.html
- name: Add APT Key for HashiCorp repository
  apt_key:
    url: "{{ apt_repos.hashicorp }}/gpg"
    state: present

# see https://docs.ansible.com/ansible/2.9/modules/apt_repository_module.html
- name: Add APT repository for HashiCorp packages
  apt_repository:
    repo: "deb [arch=amd64] {{ apt_repos.hashicorp }} {{ ansible_distribution_release | lower }} main"
    state: present
    update_cache: true

# see https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Install HashiCorp packages
  apt:
    force_apt_get: true
    install_recommends: true
    name: "{{ item.name }}={{ item.version | default('*') }}"
    state: present
    update_cache: true
  with_items: "{{ apt_packages.hashicorp }}"

# see https://docs.ansible.com/ansible/2.9/modules/template_module.html
- name: Copy Unit file
  template:
    src: templates/{{ item.name }}.service.j2
    dest: /lib/systemd/system/{{ item.name }}.service
  with_items: "{{ apt_packages.hashicorp }}"

# see https://docs.ansible.com/ansible/2.9/modules/systemd_module.html
- name: Enable HashiCorp Services
  systemd:
    state: started
    name: item.name
  with_items: "{{ apt_packages.hashicorp }}"

# TODO: add support for groups / users
