---

- name: "Provision Packer image"
  hosts: default
  become: true

  tasks:
    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html#include-module
    - name: "Manage base packages"
      include: base.yml

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html#include-module
    - name: "Manage HashiCorp packages"
      include: hashicorp.yml

    # see https://docs.ansible.com/ansible/2.9/modules/include_module.html#include-module
    - name: "Manage Docker packages"
      include: docker.yml
