---

# TODO: add support for Kubic repo: https://podman.io/getting-started/installation

# see https://docs.ansible.com/ansible/2.9/modules/apt_module.html
- name: Install Podman packages
  apt:
    force_apt_get: true
    install_recommends: true
    name: "{{ item.name }}={{ item.version | default('*') }}"
    state: present
    update_cache: true
  with_items: "{{ apt_packages.podman }}"
