---

name: "Code Quality: Packer"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  packer:
    name: packer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path: [
          "./packer/aws",
          "./packer/azure",
          "./packer/google",
          "./packer/vagrant"
        ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Format Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fmt
          target: "${{ matrix.path }}"

#      - name: Validate Template
#        uses: hashicorp/packer-github-actions@master
#        with:
#          command: validate
#          target: "${{ matrix.path }}/image.pkr.hcl"
#          arguments: "-var-file=packer/_shared/shared.pkrvars.hcl"
