---

name: "Code Quality: Terraform"

# yamllint disable-line rule:truthy
on:
  pull_request:

jobs:
  terraform:
    name: terraform
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: [
          "./terraform/azure"
        ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.4"

      - name: Run `terraform fmt`
        run: terraform -chdir="${{ matrix.directory }}" fmt -diff -check -no-color -recursive

      - name: Run `terraform init`
        run: terraform -chdir="${{ matrix.directory }}" init -backend=false -get=true

      - name: Run `terraform validate`
        run: terraform -chdir="${{ matrix.directory }}" validate -no-color
